# Generated by Django 5.0.7 on 2024-07-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="location",
            new_name="location_in",
        ),
        migrations.AddField(
            model_name="attendance",
            name="location_out",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
