# Generated by Django 5.0.7 on 2024-07-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0002_rename_location_attendance_location_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="location_in",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
