# Generated by Django 5.0.7 on 2024-07-24 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0004_district_department_district_employee_district_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="District",
            new_name="DutyStation",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="district",
            new_name="duty_station",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="district",
            new_name="duty_station",
        ),
        migrations.RenameField(
            model_name="notice",
            old_name="district",
            new_name="duty_station",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="district",
            new_name="duty_station",
        ),
        migrations.AddField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hrms.position",
            ),
        ),
    ]
