# Generated by Django 5.0.7 on 2024-07-24 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0005_position_rename_district_dutystation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="date_joined",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
