# Generated by Django 5.0.7 on 2024-07-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0006_employee_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="date_joined",
            field=models.DateField(auto_now_add=True),
        ),
    ]
