# Generated by Django 5.0.7 on 2024-08-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0007_alter_employee_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="distance_in",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="distance_out",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_in",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_out",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CentralLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "duty_station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hrms.dutystation",
                    ),
                ),
            ],
        ),
    ]
