# Generated by Django 5.0.7 on 2024-08-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0008_attendance_distance_in_attendance_distance_out_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Salary",
        ),
    ]
