from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('help/', views.help, name='help'),
    path('more/', views.more, name='more'),
    path('register/', views.register, name='register'),
    path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('payroll/', views.payroll_management, name='payroll_management'),
    path('employees/manage/', views.manage_employees, name='manage_employees'),
    path('attendance/mark/', views.mark_attendance, name='mark_attendance'),
    path('attendance/list/', views.attendance_list, name='attendance_list'),
    path('add/', views.add_attendance, name='add_attendance'),
    path('leave/apply/', views.apply_leave, name='apply_leave'),
    path('leave/list/', views.leave_list, name='leave_list'),
    path('leaves/manage/', views.manage_leaves, name='manage_leaves'),
    path('settings/', views.settings_view, name='settings'),
    path('awards/', views.awards_management, name='awards_management'),
    path('training/', views.training_management, name='training_management'),
    path('recruitment/', views.recruitment_management, name='recruitment_management'),
    path('performance/', views.performance_management, name='performance_management'),
    path('performance/review/<int:employee_id>/', views.submit_performance_review, name='submit_performance_review'),
    path('notices/', views.view_notices, name='view_notices'),
    path('notice/post/', views.post_notice, name='post_notice'),
    path('notice/<int:notice_id>/edit/', views.edit_notice, name='edit_notice'),
    path('notice/<int:notice_id>/delete/', views.delete_notice, name='delete_notice'),
    path('notice/<int:notice_id>/', views.notice_detail, name='notice_detail'),
    path('employees/add/', views.add_employee, name='add_employee'),
    path('employees/edit/<int:id>/', views.edit_employee, name='edit_employee'),
    path('employees/delete/<int:id>/', views.delete_employee, name='delete_employee'),
    path('leave_requests/', views.leave_requests, name='leave_requests'),
    path('time-sheet/', views.time_sheet, name='time_sheet'),
    path('documents/', views.documents, name='documents'),
    path('edashboard/', views.employee_dashboard, name='employee_dashboard'),
    path('profile/', views.employee_profile, name='employee_profile'),
    path('attendance/', views.employee_attendance, name='employee_attendance'),
    path('leave/request/', views.employee_leave_request, name='employee_leave_request'),
    path('leave/history/', views.employee_leave_history, name='employee_leave_history'),
    path('payslips/', views.employee_payslips, name='employee_payslips'),
    path('eperformance/', views.employee_performance, name='employee_performance'),
    path('notifications/', views.employee_notifications, name='employee_notifications'),
    path('team/', views.employee_team, name='employee_team'),
    path('check-in-out/', views.check_in_out, name='check_in_out'),
    path('attendance/edit/<int:pk>/', views.edit_attendance, name='edit_attendance'),
    path('add-department/', views.add_department, name='add_department'),
    path('departments/', views.department_list, name='department_list'),
    path('departments/edit/<int:department_id>/', views.edit_department, name='edit_department'),
    path('departments/delete/<int:department_id>/', views.delete_department, name='delete_department'),  # Add this line
    path('delete_attendance/<int:pk>/', views.delete_attendance, name='delete_attendance'),
    path('employee/<int:pk>/', views.employee_detail, name='employee_detail'),
]
